<!DOCTYPE html>
<html>
<head>
    <title>Grand Ward Rounds Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #333;
            padding-bottom: 10px;
        }
        .header h1 {
            margin: 0;
            color: #333;
        }
        .header .subtitle {
            color: #666;
            font-size: 14px;
        }
        .report-info {
            margin-bottom: 20px;
        }
        .report-info table {
            width: 100%;
            border-collapse: collapse;
        }
        .report-info td {
            padding: 5px;
        }
        .table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        .table th, .table td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        .table th {
            background-color: #f2f2f2;
            font-weight: bold;
        }
        .badge {
            padding: 2px 8px;
            border-radius: 3px;
            font-size: 11px;
            font-weight: bold;
        }
        .badge-active { background-color: #28a745; color: white; }
        .badge-inactive { background-color: #dc3545; color: white; }
        .badge-pending { background-color: #ffc107; color: black; }
        .summary {
            margin-top: 30px;
            padding: 15px;
            background-color: #f8f9fa;
            border-radius: 5px;
        }
        .footer {
            margin-top: 50px;
            text-align: center;
            color: #666;
            font-size: 11px;
            border-top: 1px solid #ddd;
            padding-top: 10px;
        }
        .page-break {
            page-break-before: always;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Grand Ward Rounds Report</h1>
        <div class="subtitle">Generated on: {{ date('d M, Y h:i A') }}</div>
    </div>

    <div class="report-info">
        <table>
            <tr>
                <td><strong>Total Records:</strong> {{ $rounds->count() }}</td>
                <td><strong>Generated By:</strong> {{ auth()->user()->name ?? 'System' }}</td>
                <td><strong>Period:</strong> All Time</td>
            </tr>
        </table>
    </div>

    @php
        $totalRounds = $rounds->count();
        $activeRounds = $rounds->where('involvement', 'A')->count();
        $waitingRounds = $rounds->where('involvement', 'W')->count();
        $passiveRounds = $rounds->where('involvement', 'P')->count();
        $activePercentage = $totalRounds > 0 ? round(($activeRounds * 100) / $totalRounds) : 0;
    @endphp

    <div class="summary">
        <h3>Summary Statistics</h3>
        <table style="width: 100%;">
            <tr>
                <td><strong>Total Rounds:</strong> {{ $totalRounds }}</td>
                <td><strong>Active Involvement:</strong> {{ $activeRounds }} ({{ $activePercentage }}%)</td>
                <td><strong>Waiting:</strong> {{ $waitingRounds }}</td>
                <td><strong>Passive:</strong> {{ $passiveRounds }}</td>
            </tr>
        </table>
    </div>

    <table class="table">
         <thead class="table-dark">
            <tr>
                <th>#</th>
                <th>Date</th>
                <th>Hospital</th>
                <th>Consultant</th>
                <th>Involvement</th>
                <th>Status</th>
                <th>Created By</th>
                <th>Created At</th>
            </tr>
        </thead>
        <tbody>
            @foreach($rounds as $index => $round)
                <tr>
                    <td>{{ $index + 1 }}</td>
                    <td>{{ $round->date->format('d/m/Y') }}</td>
                    <td>{{ $round->hospital->name ?? 'N/A' }}</td>
                    <td>{{ $round->consultant->name ?? 'N/A' }}</td>
                    <td>
                        @php
                            $involvementLabels = [
                                'A' => 'Active',
                                'W' => 'Waiting',
                                'P' => 'Passive'
                            ];
                        @endphp
                        {{ $involvementLabels[$round->involvement] ?? $round->involvement }}
                    </td>
                    <td>
                        <span class="badge badge-{{ $round->status }}">
                            {{ ucfirst($round->status) }}
                        </span>
                    </td>
                    <td>{{ $round->user->name ?? 'System' }}</td>
                    <td>{{ $round->created_at->format('d/m/Y H:i') }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    @if($rounds->count() > 0)
        <div class="page-break"></div>

        <div class="header">
            <h2>Detailed Analysis</h2>
        </div>

        <!-- Hospital-wise Distribution -->
        <h3>Hospital-wise Distribution</h3>
        <table class="table">
            <thead>
                <tr>
                    <th>Hospital</th>
                    <th>Total Rounds</th>
                    <th>Percentage</th>
                </tr>
            </thead>
            <tbody>
                @php
                    $hospitalStats = $rounds->groupBy('hospital_id')->map(function($group) {
                        return $group->count();
                    });
                @endphp
                @foreach($hospitalStats as $hospitalId => $count)
                    @php
                        $hospital = $rounds->firstWhere('hospital_id', $hospitalId)->hospital ?? null;
                        $percentage = $totalRounds > 0 ? round(($count * 100) / $totalRounds, 1) : 0;
                    @endphp
                    <tr>
                        <td>{{ $hospital->name ?? 'Unknown' }}</td>
                        <td>{{ $count }}</td>
                        <td>{{ $percentage }}%</td>
                    </tr>
                @endforeach
            </tbody>
        </table>

        <!-- Consultant-wise Distribution -->
        <h3>Consultant-wise Distribution</h3>
        <table class="table">
            <thead>
                <tr>
                    <th>Consultant</th>
                    <th>Total Rounds</th>
                    <th>Active</th>
                    <th>Waiting</th>
                    <th>Passive</th>
                </tr>
            </thead>
            <tbody>
                @php
                    $consultantStats = $rounds->groupBy('consultant_id');
                @endphp
                @foreach($consultantStats as $consultantId => $group)
                    @php
                        $consultant = $group->first()->consultant ?? null;
                        $active = $group->where('involvement', 'A')->count();
                        $waiting = $group->where('involvement', 'W')->count();
                        $passive = $group->where('involvement', 'P')->count();
                    @endphp
                    <tr>
                        <td>{{ $consultant->name ?? 'Unknown' }}</td>
                        <td>{{ $group->count() }}</td>
                        <td>{{ $active }}</td>
                        <td>{{ $waiting }}</td>
                        <td>{{ $passive }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>

        <!-- Monthly Trend -->
        <h3>Monthly Trend (Last 6 Months)</h3>
        <table class="table">
            <thead>
                <tr>
                    <th>Month</th>
                    <th>Total Rounds</th>
                    <th>Active</th>
                    <th>Growth</th>
                </tr>
            </thead>
            <tbody>
                @php
                    $sixMonthsAgo = \Carbon\Carbon::now()->subMonths(6)->startOfMonth();
                    $monthlyData = $rounds->where('date', '>=', $sixMonthsAgo)
                                          ->groupBy(function($item) {
                                              return $item->date->format('Y-m');
                                          })->map(function($group) {
                                              return [
                                                  'total' => $group->count(),
                                                  'active' => $group->where('involvement', 'A')->count()
                                              ];
                                          })->sortKeys();
                @endphp
                @foreach($monthlyData as $month => $data)
                    <tr>
                        <td>{{ \Carbon\Carbon::parse($month)->format('M Y') }}</td>
                        <td>{{ $data['total'] }}</td>
                        <td>{{ $data['active'] }}</td>
                        <td>
                            @php
                                $prevMonth = \Carbon\Carbon::parse($month)->subMonth()->format('Y-m');
                                $prevData = $monthlyData[$prevMonth] ?? ['total' => 0];
                                $growth = $prevData['total'] > 0
                                    ? round((($data['total'] - $prevData['total']) * 100) / $prevData['total'])
                                    : 0;
                                $growthClass = $growth > 0 ? 'text-success' : ($growth < 0 ? 'text-danger' : 'text-muted');
                            @endphp
                            <span class="{{ $growthClass }}">
                                {{ $growth > 0 ? '+' : '' }}{{ $growth }}%
                            </span>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    @endif


</body>
</html>
